### ISSUE TITLE
Crashes TextMate version 2.0-beta.6.6

### ISSUE THREAD

**Issue by dandehavilland** [Mr0grog/editorconfig-textmate#18]
Crash log available here:  https://api.textmate.org/crashes/271167

**Comment by Mr0grog** [comment]
Hmm, looks like I need login info to see that.

**Comment by dandehavilland** [comment]
Hmm strange, I didn't know about that. I'll reproduce and send it over from my work machine tomorrow.

**Comment by Mr0grog** [comment]
Thanks! FWIW, I’m running on beta.6.6 without issues. It could be something particular about your `.editorconfig` files or directory structure that I just haven’t run into with any of my projects, so could you send/describe those, too?

Another possibility is some conflict with another plugin; do you have any others installed?

**Comment by dandehavilland** [comment]
Yep, you're right. I tried this on another machine and it works without any problems on beta.6.6

**Comment by Mr0grog** [comment]
@dandehavilland if you have other plugins and can let me know what they are, I’ll try and see if there are any obvious conflicts when I have some time. If there’s an easy fix I can make (or recommend to the other plugin’s developer) I’d be happy to do it :)

**Comment by dandehavilland** [comment]
I've moved on to TM2 beta.6.7, same problem. 

There are no other plugins installed but this only happens on one of my machines so it must be a problem with my setup. I'm going to clear and reinstall TM2 and all the prefs, maybe that will resolve it.

Either way, my .editorconfig and a fresh crash report are here in case they are useful: https://gist.github.com/dandehavilland/e258744bfe16ebab1738

**Comment by Mr0grog** [comment]
Hmm, nothing in that crash report would seem to indicate it’s the plug-in… I’m assuming you tried it and couldn’t reproduce without the plug-in installed, though? Do you have steps to reproduce? Does it crash when you do something in particular? Is it just crashing on startup?

**Comment by dandehavilland** [comment]
I could only reproduce the crash with the plugin installed, when opening a file within a directory that contains a `.editorconfig` file. Must be something in my local environment so I wouldn't worry about it.

**Comment by Mr0grog** [comment]
Ok, I’ll leave it, then.
