### ISSUE TITLE
Silly question, but how can I tell if it's working?

### ISSUE THREAD

**Issue by danieljimenez** [Mr0grog/editorconfig-textmate#32]
Silly question, but how can I tell if it's working? I see no logs or indication the plug-in is installed.

**Comment by Mr0grog** [comment]
It’s… pretty silent. It just attempts to follow your `.editorconfig` file without making a fuss, so the best thing you can do is open a few files that would have different settings according to your `.editorconfig` file and make sure they are reflected properly when you edit. The spaces/tabs size controls at the bottom of the window should match your config file, for example.

At some point it’d be great to have UI that indicates whether things parsed correctly or not and maybe even a settings panel, but I haven’t had time to work on those and haven’t seen much demand from people.

**Comment by danieljimenez** [comment]
Gotcha, I forgot to ask about the controls at the bottom. I'll give that a shot! Thanks!

**Comment by danieljimenez** [comment]
Also, thanks for putting together the plugin 🥇
