### ISSUE TITLE
Plugin not loaded after installation

### ISSUE THREAD

**Issue by webmaster128** [Mr0grog/editorconfig-textmate#33]
Hi and thanks for doing this!

I just installed the prebuild plugin (0.3.0) into `~/Library/Application\ Support/TextMate/PlugIns` but after restarting TextMate, the Plugin is not listed in the Preferences -> Bundles list.

Do I need to enable plugin search in this directory somehow? Note that all the default Bundles are stored somewhere else.

Any idea how to debug this?

---------

TextMate version 2.0-rc.4

```
$ ls ~/Library/Application\ Support/TextMate/PlugIns 
editorconfig-textmate.tmplugin
```

```
$ cat ~/Library/Application\ Support/TextMate/PlugIns/editorconfig-textmate.tmplugin/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16C67</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>editorconfig-textmate</string>
	<key>CFBundleIdentifier</key>
	<string>org.robbrackett.editorconfig-textmate</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>editorconfig-textmate</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.3.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>0.3.0</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8C1002</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16C58</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0821</string>
	<key>DTXcodeBuild</key>
	<string>8C1002</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2012-2017 Rob Brackett. This is open source software and released under the MIT license.</string>
	<key>NSPrincipalClass</key>
	<string>ECEditorConfig</string>
	<key>TMPlugInAPIVersion</key>
	<integer>2</integer>
</dict>
</plist>
```

**Comment by Mr0grog** [comment]
> after restarting TextMate, the Plugin is not listed in the Preferences -> Bundles list.

Ah, that is because it’s not a bundle (those are different from plug-ins in TextMate), so it won’t be listed there. There is no mechanism in TextMate that displays loaded plug-ins to users :(

Adding some UI that provides more feedback is something I’d love to do (see #32), but simply haven’t had time for. You can test that the plug-in is working by creating a `.editorconfig` file and making sure its effects work as expected (e.g. the tab type/size selector at the bottom of the window should reflect the correct value for the current document, trailing spaces should be eliminated when saving, and so on, based on your settings).

**Comment by webmaster128** [comment]
Perfect thanks. I did not realize it is working because I missed to configure `trim_trailing_whitespace`.

I guess a short note to the installation README can avoid most confusion here, so a visible sign of life may be nice to have.
