### ISSUE TITLE
Sets tab width instead of max line length

### ISSUE THREAD

**Issue by elia** [Mr0grog/editorconfig-textmate#36]
The following configuration is setting tab width to 80:

_the file of the screenshot is located at vendor/spree-06a7120d25d5/backend/app/controllers/spree/admin/taxons_controller.rb_
<img width="517" alt="screen shot 2017-05-05 at 12 28 57" src="https://cloud.githubusercontent.com/assets/1051/25742155/7490d3a6-318e-11e7-9335-29b7dd1269b2.png">

_vendor/spree-06a7120d25d5/.editorconfig_

```ini
# http://EditorConfig.org
# https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
tab_width = 2

[**.rb]
max_line_length = 80

[**.js, **.coffee]
max_line_length = 120

[*.md]
trim_trailing_whitespace = false
```

**Comment by Mr0grog** [comment]
Hmmmm, looking at the same file, I’m not seeing this behavior. What version of the plugin and of TextMate are you using?

**Comment by elia** [comment]
TextMate version 2.0-rc.4

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16C67</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>editorconfig-textmate</string>
	<key>CFBundleIdentifier</key>
	<string>org.robbrackett.editorconfig-textmate</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>editorconfig-textmate</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.3.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>0.3.0</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8C1002</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16C58</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0821</string>
	<key>DTXcodeBuild</key>
	<string>8C1002</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2012-2017 Rob Brackett. This is open source software and released under the MIT license.</string>
	<key>NSPrincipalClass</key>
	<string>ECEditorConfig</string>
	<key>TMPlugInAPIVersion</key>
	<integer>2</integer>
</dict>
</plist>
```

no other plugins are installed

**Comment by Mr0grog** [comment]
Oh, geez, nevermind. Looks like I fixed this [over two months ago](https://github.com/Mr0grog/editorconfig-textmate/commit/29f77f18892dc2db256feb4a5e93efde78fa0ee6) but failed to ever publish it! SO Sorry. Will get a fixed release up shortly.

**Comment by Mr0grog** [comment]
Ok, you should be able to grab v0.3.1, which will fix your problem, here: https://github.com/Mr0grog/editorconfig-textmate/releases/tag/v0.3.1

If it works for you, please close this issue. Otherwise, post back and let me know it’s still not working in your environment!

**Comment by elia** [comment]
Great, It works!

(as a side note: would be great if there was a way to update from within textmate, also I had to remove the old version manually in order to make it work)

**Comment by Mr0grog** [comment]
Huh, I did not realize you have to remove old ones manually. Maybe worth filing an issue on TextMate for that? I would have thought it would take the newer one since the bundle version is newer :\
