### ISSUE TITLE
Update to EditorConfig C Core 0.12.9

### ISSUE THREAD

**Issue by xuhdev** [Mr0grog/editorconfig-textmate#54]
EditorConfig C Core 0.12.9 fixed an issue that may crash: https://github.com/editorconfig/editorconfig-core-c/releases/tag/v0.12.9

This is a relatively serious bug introduced in 0.12.8 IMO. Since it was released only a few days after 0.12.8, guess you may have missed it.

**Comment by Mr0grog** [comment]
Thanks for the push on this! 👍
